In [1]:
# 矩阵的奇异值分解
import numpy as np
A = np.array([[1,2],
	        [1,1],
	        [0,0]])

In [2]:
print(A.T)

[[1 1 0]
 [2 1 0]]


In [3]:
temp1 = np.dot(A, A.T)
temp2 = np.dot(A.T, A)
print(temp1)
print(temp2)

[[5 3 0]
 [3 2 0]
 [0 0 0]]
[[2 3]
 [3 5]]


In [4]:
#A = np.array([[5,1],
#	        [1,1]])

In [5]:
lamda1, U1 = np.linalg.eig(temp1)
print(lamda1)
print(U1)
lamda2, U2 = np.linalg.eig(temp2)
print(lamda2)
print(U2)

[6.85410197 0.14589803 0.        ]
[[ 0.85065081 -0.52573111  0.        ]
 [ 0.52573111  0.85065081  0.        ]
 [ 0.          0.          1.        ]]
[0.14589803 6.85410197]
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
