In [1]:
import numpy as np

In [2]:
a = np.array([[0, 12, 999, 999, 999, 16, 14], 
			  [12, 0, 10,  999, 999, 7, 999],
			  [999,10, 0,  3,   5,   6, 999],
			  [999,999,3,  0,   4,  999,999],
			  [999,999,5,  4,   0,   2, 8],
			  [16, 7,  6, 999,  2,   0, 9],
			  [14, 999,999,999, 8,   9, 0]])

In [3]:
n = 7

In [4]:
# 使用Floyed算法
for k in range(0, n):
    for i in range(0, n):
        for j in range(0, n):
            if a[i][k] + a[k][j] < a[i][j]:
                a[i][j] = a[i][k] + a[k][j]

In [5]:
# 输出结果
print('各城市之间的最短距离: ', a)
print('城市D到其他城市的最短距离: ', a[3])

各城市之间的最短距离:  [[ 0 12 22 22 18 16 14]
 [12  0 10 13  9  7 16]
 [22 10  0  3  5  6 13]
 [22 13  3  0  4  6 12]
 [18  9  5  4  0  2  8]
 [16  7  6  6  2  0  9]
 [14 16 13 12  8  9  0]]
城市D到其他城市的最短距离:  [22 13  3  0  4  6 12]
