In [1]:
import numpy as np

In [2]:
a = np.array([[0, 1/2, 1, 0],
            [1/3, 0, 0, 1/2],
            [1/3, 0, 0, 1/2],
            [1/3, 1/2, 0, 0]])

In [3]:
a_leak = np.array([[0, 0, 0, 1/2],
                [0, 0, 0, 1/2],
                [0, 1, 0, 0],
                [0, 0, 1, 0]])

In [4]:
a_sink = np.array([[0, 0, 0, 0],
                [1/2, 0, 0, 1],
                [0, 1, 1, 0],
                [1/2, 0, 0, 0]])

In [5]:
b = np.array([1/4, 1/4, 1/4, 1/4])
w = b

In [6]:
def work(a, w):
    for i in range(100):
        w = np.dot(a, w)
        print(w)

In [7]:
def random_work(a, w, n):
    d = 0.85
    for i in range(100):
        w = (1-d)/n + d*np.dot(a, w)
        print(w)

In [8]:
work(a, w)

[0.375      0.20833333 0.20833333 0.20833333]
[0.3125     0.22916667 0.22916667 0.22916667]
[0.34375 0.21875 0.21875 0.21875]
[0.328125   0.22395833 0.22395833 0.22395833]
[0.3359375  0.22135417 0.22135417 0.22135417]
[0.33203125 0.22265625 0.22265625 0.22265625]
[0.33398438 0.22200521 0.22200521 0.22200521]
[0.33300781 0.22233073 0.22233073 0.22233073]
[0.33349609 0.22216797 0.22216797 0.22216797]
[0.33325195 0.22224935 0.22224935 0.22224935]
[0.33337402 0.22220866 0.22220866 0.22220866]
[0.33331299 0.222229   0.222229   0.222229  ]
[0.33334351 0.22221883 0.22221883 0.22221883]
[0.33332825 0.22222392 0.22222392 0.22222392]
[0.33333588 0.22222137 0.22222137 0.22222137]
[0.33333206 0.22222265 0.22222265 0.22222265]
[0.33333397 0.22222201 0.22222201 0.22222201]
[0.33333302 0.22222233 0.22222233 0.22222233]
[0.33333349 0.22222217 0.22222217 0.22222217]
[0.33333325 0.22222225 0.22222225 0.22222225]
[0.33333337 0.22222221 0.22222221 0.22222221]
[0.33333331 0.22222223 0.22222223 0.22222223]


In [9]:
random_work(a, w, 4)

[0.35625    0.21458333 0.21458333 0.21458333]
[0.31109375 0.22963542 0.22963542 0.22963542]
[0.33028516 0.22323828 0.22323828 0.22323828]
[0.32212881 0.22595706 0.22595706 0.22595706]
[0.32559526 0.22480158 0.22480158 0.22480158]
[0.32412202 0.22529266 0.22529266 0.22529266]
[0.32474814 0.22508395 0.22508395 0.22508395]
[0.32448204 0.22517265 0.22517265 0.22517265]
[0.32459513 0.22513496 0.22513496 0.22513496]
[0.32454707 0.22515098 0.22515098 0.22515098]
[0.3245675  0.22514417 0.22514417 0.22514417]
[0.32455881 0.22514706 0.22514706 0.22514706]
[0.3245625  0.22514583 0.22514583 0.22514583]
[0.32456094 0.22514635 0.22514635 0.22514635]
[0.3245616  0.22514613 0.22514613 0.22514613]
[0.32456132 0.22514623 0.22514623 0.22514623]
[0.32456144 0.22514619 0.22514619 0.22514619]
[0.32456139 0.2251462  0.2251462  0.2251462 ]
[0.32456141 0.2251462  0.2251462  0.2251462 ]
[0.3245614 0.2251462 0.2251462 0.2251462]
[0.3245614 0.2251462 0.2251462 0.2251462]
[0.3245614 0.2251462 0.2251462 0.2251462]


In [10]:
random_work(a_leak, w, 4)

[0.14375 0.14375 0.25    0.25   ]
[0.14375   0.14375   0.1596875 0.25     ]
[0.14375    0.14375    0.1596875  0.17323437]
[0.11112461 0.11112461 0.1596875  0.17323437]
[0.11112461 0.11112461 0.13195592 0.17323437]
[0.11112461 0.11112461 0.13195592 0.14966253]
[0.10110658 0.10110658 0.13195592 0.14966253]
[0.10110658 0.10110658 0.12344059 0.14966253]
[0.10110658 0.10110658 0.12344059 0.1424245 ]
[0.09803041 0.09803041 0.12344059 0.1424245 ]
[0.09803041 0.09803041 0.12082585 0.1424245 ]
[0.09803041 0.09803041 0.12082585 0.14020197]
[0.09708584 0.09708584 0.12082585 0.14020197]
[0.09708584 0.09708584 0.12002296 0.14020197]
[0.09708584 0.09708584 0.12002296 0.13951952]
[0.0967958  0.0967958  0.12002296 0.13951952]
[0.0967958  0.0967958  0.11977643 0.13951952]
[0.0967958  0.0967958  0.11977643 0.13930996]
[0.09670673 0.09670673 0.11977643 0.13930996]
[0.09670673 0.09670673 0.11970072 0.13930996]
[0.09670673 0.09670673 0.11970072 0.13924562]
[0.09667939 0.09667939 0.11970072 0.13924562]
[0.0

In [11]:
random_work(a_sink, w, 4)

[0.0375  0.35625 0.4625  0.14375]
[0.0375    0.175625  0.7334375 0.0534375]
[0.0375     0.09885938 0.81020312 0.0534375 ]
[0.0375     0.09885938 0.81020312 0.0534375 ]
[0.0375     0.09885938 0.81020312 0.0534375 ]
[0.0375     0.09885938 0.81020312 0.0534375 ]
[0.0375     0.09885938 0.81020312 0.0534375 ]
[0.0375     0.09885938 0.81020312 0.0534375 ]
[0.0375     0.09885938 0.81020312 0.0534375 ]
[0.0375     0.09885938 0.81020312 0.0534375 ]
[0.0375     0.09885938 0.81020312 0.0534375 ]
[0.0375     0.09885938 0.81020312 0.0534375 ]
[0.0375     0.09885938 0.81020312 0.0534375 ]
[0.0375     0.09885938 0.81020312 0.0534375 ]
[0.0375     0.09885938 0.81020312 0.0534375 ]
[0.0375     0.09885938 0.81020312 0.0534375 ]
[0.0375     0.09885938 0.81020312 0.0534375 ]
[0.0375     0.09885938 0.81020312 0.0534375 ]
[0.0375     0.09885938 0.81020312 0.0534375 ]
[0.0375     0.09885938 0.81020312 0.0534375 ]
[0.0375     0.09885938 0.81020312 0.0534375 ]
[0.0375     0.09885938 0.81020312 0.0534375 ]
[0.0