In [1]:
from sklearn import preprocessing
import numpy as np

x = np.array([[1.,-1,2.],
             [2.,0.,0.],
             [0.,1.,-1.]])
x_scale = preprocessing.scale(x)
x_scale

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [2]:
x_scale.shape

(3, 3)

In [3]:
# axis=0 表示对每一列 
x_scale.mean(axis=0)

array([0., 0., 0.])

In [4]:
# axis=1表示对每一行
x_scale.mean(axis=1)

array([ 0.03718711,  0.31916121, -0.35634832])

In [5]:
# 同理,看一下标准差
x_scale.std(axis=0)

array([1., 1., 1.])

In [8]:
scaler = preprocessing.StandardScaler().fit(x)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [9]:
# 使用上面这个转换器去转换训练数据x,调用transform方法
scaler.transform(x)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [10]:
#################################################
# 现在又来了一组新的样本,也想得到相同的转换
new_x = [[-1,1,0]]
scaler.transform(new_x)

array([[-2.44948974,  1.22474487, -0.26726124]])

In [13]:
min_max_scaler = preprocessing.MinMaxScaler()
x_minmax = min_max_scaler.fit_transform(x)
x_minmax

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [14]:
# 同样的,如果有新的测试数据进来,也想做同样的转换
x_test= np.array([[-3.,-1.,4,]])
x_test_minmax = min_max_scaler.transform(x_test)
x_test_minmax

array([[-1.5       ,  0.        ,  1.66666667]])

In [1]:
import numpy as np
from sklearn.metrics import accuracy_score
y_pred = [0,2,1,3]
y_true = [0,1,2,3]
accuracy_score(y_true,y_pred)

0.5

In [2]:
accuracy_score(y_true,y_pred,normalize=False)

2